export const LANGUAGES = [
  { label: "A# .NET", value: "aNet" },
  { label: "A# (Axiom)", value: "aAxiom" },
  { label: "A-0 System", value: "a0System" },
  { label: "A+", value: "a" },
  { label: "A++", value: "a" },
  { label: "ABAP", value: "abap" },
  { label: "ABC", value: "abc" },
  { label: "ABC ALGOL", value: "abcAlgol" },
  { label: "ABLE", value: "able" },
  { label: "ABSET", value: "abset" },
  { label: "ABSYS", value: "absys" },
  { label: "ACC", value: "acc" },
  { label: "Accent", value: "accent" },
  { label: "Ace DASL", value: "aceDasl" },
  { label: "ACL2", value: "acl2" },
  { label: "ACT-III", value: "actIii" },
  { label: "Action!", value: "action" },
  { label: "ActionScript", value: "actionScript" },
  { label: "Ada", value: "ada" },
  { label: "Adenine", value: "adenine" },
  { label: "Agda", value: "agda" },
  { label: "Agilent VEE", value: "agilentVee" },
  { label: "Agora", value: "agora" },
  { label: "AIMMS", value: "aimms" },
  { label: "Alef", value: "alef" },
  { label: "ALF", value: "alf" },
  { label: "ALGOL 58", value: "algol58" },
  { label: "ALGOL 60", value: "algol60" },
  { label: "ALGOL 68", value: "algol68" },
  { label: "ALGOL W", value: "algolW" },
  { label: "Alice", value: "alice" },
  { label: "Alma-0", value: "alma0" },
  { label: "AmbientTalk", value: "ambientTalk" },
  { label: "Amiga E", value: "amigaE" },
  { label: "AMOS", value: "amos" },
  { label: "AMPL", value: "ampl" },
  { label: "APL", value: "apl" },
  {
    label: "App Inventor for Android's visual block language",
    value: "appInventorForAndroidsVisualBlockLanguage",
  },
  { label: "AppleScript", value: "appleScript" },
  { label: "Arc", value: "arc" },
  { label: "ARexx", value: "aRexx" },
  { label: "Argus", value: "argus" },
  { label: "AspectJ", value: "aspectJ" },
  { label: "Assembly language", value: "assemblyLanguage" },
  { label: "ATS", value: "ats" },
  { label: "Ateji PX", value: "atejiPx" },
  { label: "AutoHotkey", value: "autoHotkey" },
  { label: "Autocoder", value: "autocoder" },
  { label: "AutoIt", value: "autoIt" },
  { label: "AutoLISP / Visual LISP", value: "autoLispVisualLisp" },
  { label: "Averest", value: "averest" },
  { label: "AWK", value: "awk" },
  { label: "Axum", value: "axum" },
  { label: "B", value: "b" },
  { label: "Babbage", value: "babbage" },
  { label: "Bash", value: "bash" },
  { label: "BASIC", value: "basic" },
  { label: "bc", value: "bc" },
  { label: "BCPL", value: "bcpl" },
  { label: "BeanShell", value: "beanShell" },
  { label: "Batch (Windows/Dos)", value: "batchWindowsDos" },
  { label: "Bertrand", value: "bertrand" },
  { label: "BETA", value: "beta" },
  { label: "Bigwig", value: "bigwig" },
  { label: "Bistro", value: "bistro" },
  { label: "BitC", value: "bitC" },
  { label: "BLISS", value: "bliss" },
  { label: "Blue", value: "blue" },
  { label: "Bon", value: "bon" },
  { label: "Boo", value: "boo" },
  { label: "Boomerang", value: "boomerang" },
  { label: "Bourne shell", value: "bourneShell" },
  { label: "ksh", value: "ksh" },
  { label: "BREW", value: "brew" },
  { label: "BPEL", value: "bpel" },
  { label: "C", value: "c" },
  { label: "C--", value: "cmm" },
  { label: "C++", value: "cpp" },
  { label: "C#", value: "cs" },
  { label: "C/AL", value: "cAl" },
  { label: "Caché ObjectScript", value: "cacheObjectScript" },
  { label: "C Shell", value: "cShell" },
  { label: "Caml", value: "caml" },
  { label: "Candle", value: "candle" },
  { label: "Cayenne", value: "cayenne" },
  { label: "CDuce", value: "cDuce" },
  { label: "Cecil", value: "cecil" },
  { label: "Cel", value: "cel" },
  { label: "Cesil", value: "cesil" },
  { label: "Ceylon", value: "ceylon" },
  { label: "CFEngine", value: "cfEngine" },
  { label: "CFML", value: "cfml" },
  { label: "Cg", value: "cg" },
  { label: "Ch", value: "ch" },
  { label: "Chapel", value: "chapel" },
  { label: "CHAIN", value: "chain" },
  { label: "Charity", value: "charity" },
  { label: "Charm", value: "charm" },
  { label: "Chef", value: "chef" },
  { label: "CHILL", value: "chill" },
  { label: "CHIP-8", value: "chip8" },
  { label: "chomski", value: "chomski" },
  { label: "ChucK", value: "chucK" },
  { label: "CICS", value: "cics" },
  { label: "Cilk", value: "cilk" },
  { label: "CL", value: "cl" },
  { label: "Claire", value: "claire" },
  { label: "Clarion", value: "clarion" },
  { label: "Clean", value: "clean" },
  { label: "Clipper", value: "clipper" },
  { label: "CLIST", value: "clist" },
  { label: "Clojure", value: "clojure" },
  { label: "CLU", value: "clu" },
  { label: "CMS-2", value: "cms2" },
  { label: "COBOL", value: "cobol" },
  { label: "Cobra", value: "cobra" },
  { label: "CODE", value: "code" },
  { label: "CoffeeScript", value: "coffeeScript" },
  { label: "Cola", value: "cola" },
  { label: "ColdC", value: "coldC" },
  { label: "ColdFusion", value: "coldFusion" },
  { label: "COMAL", value: "comal" },
  {
    label: "Combined Programming Language",
    value: "combinedProgrammingLanguage",
  },
  { label: "COMIT", value: "comit" },
  {
    label: "Common Intermediate Language",
    value: "commonIntermediateLanguage",
  },
  { label: "Common Lisp", value: "commonLisp" },
  { label: "COMPASS", value: "compass" },
  { label: "Component Pascal", value: "componentPascal" },
  { label: "Constraint Handling Rules", value: "constraintHandlingRules" },
  { label: "Converge", value: "converge" },
  { label: "Cool", value: "cool" },
  { label: "Coq", value: "coq" },
  { label: "Coral 66", value: "coral66" },
  { label: "Corn", value: "corn" },
  { label: "CorVision", value: "corVision" },
  { label: "COWSEL", value: "cowsel" },
  { label: "CPL", value: "cpl" },
  { label: "csh", value: "csh" },
  { label: "CSP", value: "csp" },
  { label: "CSS", value: "css" },
  { label: "Csound", value: "csound" },
  { label: "CUDA", value: "cuda" },
  { label: "Curl", value: "curl" },
  { label: "Curry", value: "curry" },
  { label: "Cyclone", value: "cyclone" },
  { label: "Cython", value: "cython" },
  { label: "D", value: "d" },
  { label: "DASL", value: "dasl" },
  { label: "DASL", value: "dasl" },
  { label: "Dart", value: "dart" },
  { label: "DataFlex", value: "dataFlex" },
  { label: "Datalog", value: "datalog" },
  { label: "DATATRIEVE", value: "datatrieve" },
  { label: "dBase", value: "dBase" },
  { label: "dc", value: "dc" },
  { label: "DCL", value: "dcl" },
  { label: "Deesel", value: "deesel" },
  { label: "Delphi", value: "delphi" },
  { label: "DinkC", value: "dinkC" },
  { label: "DIBOL", value: "dibol" },
  { label: "Dog", value: "dog" },
  { label: "Draco", value: "draco" },
  { label: "DRAKON", value: "drakon" },
  { label: "Dylan", value: "dylan" },
  { label: "DYNAMO", value: "dynamo" },
  { label: "E", value: "e" },
  { label: "E#", value: "e" },
  { label: "Ease", value: "ease" },
  { label: "Easy PL/I", value: "easyPlI" },
  { label: "Easy Programming Language", value: "easyProgrammingLanguage" },
  { label: "EASYTRIEVE PLUS", value: "easytrievePlus" },
  { label: "ECMAScript", value: "ecmaScript" },
  { label: "Edinburgh IMP", value: "edinburghImp" },
  { label: "EGL", value: "egl" },
  { label: "Eiffel", value: "eiffel" },
  { label: "ELAN", value: "elan" },
  { label: "Elixir", value: "elixir" },
  { label: "Elm", value: "elm" },
  { label: "Emacs Lisp", value: "emacsLisp" },
  { label: "Emerald", value: "emerald" },
  { label: "Epigram", value: "epigram" },
  { label: "EPL", value: "epl" },
  { label: "Erlang", value: "erlang" },
  { label: "es", value: "es" },
  { label: "Escapade", value: "escapade" },
  { label: "Escher", value: "escher" },
  { label: "ESPOL", value: "espol" },
  { label: "Esterel", value: "esterel" },
  { label: "Etoys", value: "etoys" },
  { label: "Euclid", value: "euclid" },
  { label: "Euler", value: "euler" },
  { label: "Euphoria", value: "euphoria" },
  {
    label: "EusLisp Robot Programming Language",
    value: "eusLispRobotProgrammingLanguage",
  },
  { label: "CMS EXEC", value: "cmsExec" },
  { label: "EXEC 2", value: "exec2" },
  { label: "Executable UML", value: "executableUml" },
  { label: "F", value: "f" },
  { label: "F#", value: "f" },
  { label: "Factor", value: "factor" },
  { label: "Falcon", value: "falcon" },
  { label: "Fancy", value: "fancy" },
  { label: "Fantom", value: "fantom" },
  { label: "FAUST", value: "faust" },
  { label: "Felix", value: "felix" },
  { label: "Ferite", value: "ferite" },
  { label: "FFP", value: "ffp" },
  { label: "Fjölnir", value: "fjolnir" },
  { label: "FL", value: "fl" },
  { label: "Flavors", value: "flavors" },
  { label: "Flex", value: "flex" },
  { label: "FLOW-MATIC", value: "flowMatic" },
  { label: "FOCAL", value: "focal" },
  { label: "FOCUS", value: "focus" },
  { label: "FOIL", value: "foil" },
  { label: "FORMAC", value: "formac" },
  { label: "@Formula", value: "formula" },
  { label: "Forth", value: "forth" },
  { label: "Fortran", value: "fortran" },
  { label: "Fortress", value: "fortress" },
  { label: "FoxBase", value: "foxBase" },
  { label: "FoxPro", value: "foxPro" },
  { label: "FP", value: "fp" },
  { label: "FPr", value: "fPr" },
  { label: "Franz Lisp", value: "franzLisp" },
  { label: "Frege", value: "frege" },
  { label: "F-Script", value: "fScript" },
  { label: "FSProg", value: "fsProg" },
  { label: "G", value: "g" },
  { label: "Google Apps Script", value: "googleAppsScript" },
  { label: "Game Maker Language", value: "gameMakerLanguage" },
  { label: "GameMonkey Script", value: "gameMonkeyScript" },
  { label: "GAMS", value: "gams" },
  { label: "GAP", value: "gap" },
  { label: "G-code", value: "gCode" },
  { label: "Genie", value: "genie" },
  { label: "GDL", value: "gdl" },
  { label: "Gibiane", value: "gibiane" },
  { label: "GJ", value: "gj" },
  { label: "GEORGE", value: "george" },
  { label: "GLSL", value: "glsl" },
  { label: "GNU E", value: "gnuE" },
  { label: "GM", value: "gm" },
  { label: "Go", value: "go" },
  { label: "Go!", value: "go" },
  { label: "GOAL", value: "goal" },
  { label: "Gödel", value: "godel" },
  { label: "Godiva", value: "godiva" },
  { label: "GOM (Good Old Mad)", value: "gomGoodOldMad" },
  { label: "Goo", value: "goo" },
  { label: "Gosu", value: "gosu" },
  { label: "GOTRAN", value: "gotran" },
  { label: "GPSS", value: "gpss" },
  { label: "GraphTalk", value: "graphTalk" },
  { label: "GRASS", value: "grass" },
  { label: "Groovy", value: "groovy" },
  { label: "Hack (programming language)", value: "hackProgrammingLanguage" },
  { label: "HAL/S", value: "halS" },
  { label: "Hamilton C shell", value: "hamiltonCShell" },
  { label: "Harbour", value: "harbour" },
  { label: "Hartmann pipelines", value: "hartmannPipelines" },
  { label: "Haskell", value: "haskell" },
  { label: "Haxe", value: "haxe" },
  { label: "High Level Assembly", value: "highLevelAssembly" },
  { label: "HLSL", value: "hlsl" },
  { label: "Hop", value: "hop" },
  { label: "Hope", value: "hope" },
  { label: "HTML", value: "html" },
  { label: "Hugo", value: "hugo" },
  { label: "Hume", value: "hume" },
  { label: "HyperTalk", value: "hyperTalk" },
  {
    label: "IBM Basic assembly language",
    value: "ibmBasicAssemblyLanguage",
  },
  { label: "IBM HAScript", value: "ibmHaScript" },
  { label: "IBM Informix-4GL", value: "ibmInformix4Gl" },
  { label: "IBM RPG", value: "ibmRpg" },
  { label: "ICI", value: "ici" },
  { label: "Icon", value: "icon" },
  { label: "Id", value: "id" },
  { label: "IDL", value: "idl" },
  { label: "Idris", value: "idris" },
  { label: "IMP", value: "imp" },
  { label: "Inform", value: "inform" },
  { label: "Io", value: "io" },
  { label: "Ioke", value: "ioke" },
  { label: "IPL", value: "ipl" },
  { label: "IPTSCRAE", value: "iptscrae" },
  { label: "ISLISP", value: "islisp" },
  { label: "ISPF", value: "ispf" },
  { label: "ISWIM", value: "iswim" },
  { label: "J", value: "j" },
  { label: "J#", value: "j" },
  { label: "J++", value: "j" },
  { label: "JADE", value: "jade" },
  { label: "Jako", value: "jako" },
  { label: "JAL", value: "jal" },
  { label: "Janus", value: "janus" },
  { label: "JASS", value: "jass" },
  { label: "Java", value: "java" },
  { label: "JavaScript", value: "javaScript" },
  { label: "JCL", value: "jcl" },
  { label: "JEAN", value: "jean" },
  { label: "Join Java", value: "joinJava" },
  { label: "JOSS", value: "joss" },
  { label: "Joule", value: "joule" },
  { label: "JOVIAL", value: "jovial" },
  { label: "Joy", value: "joy" },
  { label: "JScript", value: "jScript" },
  { label: "JScript .NET", value: "jScriptNet" },
  { label: "JavaFX Script", value: "javaFxScript" },
  { label: "Julia", value: "julia" },
  { label: "Jython", value: "jython" },
  { label: "K", value: "k" },
  { label: "Kaleidoscope", value: "kaleidoscope" },
  { label: "Karel", value: "karel" },
  { label: "Karel++", value: "karel" },
  { label: "KEE", value: "kee" },
  { label: "Kixtart", value: "kixtart" },
  { label: "KIF", value: "kif" },
  { label: "Kojo", value: "kojo" },
  { label: "Kotlin", value: "kotlin" },
  { label: "KRC", value: "krc" },
  { label: "KRL", value: "krl" },
  { label: "KUKA", value: "kuka" },
  { label: "KRYPTON", value: "krypton" },
  { label: "ksh", value: "ksh" },
  { label: "L", value: "l" },
  { label: "L# .NET", value: "lNet" },
  { label: "LabVIEW", value: "labView" },
  { label: "Ladder", value: "ladder" },
  { label: "Lagoona", value: "lagoona" },
  { label: "LANSA", value: "lansa" },
  { label: "Lasso", value: "lasso" },
  { label: "LaTeX", value: "laTeX" },
  { label: "Lava", value: "lava" },
  { label: "LC-3", value: "lc3" },
  { label: "Leda", value: "leda" },
  { label: "Legoscript", value: "legoscript" },
  { label: "LIL", value: "lil" },
  { label: "LilyPond", value: "lilyPond" },
  { label: "Limbo", value: "limbo" },
  { label: "Limnor", value: "limnor" },
  { label: "LINC", value: "linc" },
  { label: "Lingo", value: "lingo" },
  { label: "Linoleum", value: "linoleum" },
  { label: "LIS", value: "lis" },
  { label: "LISA", value: "lisa" },
  { label: "Lisaac", value: "lisaac" },
  { label: "Lisp", value: "lisp" },
  { label: "Lite-C", value: "liteC" },
  { label: "Lithe", value: "lithe" },
  { label: "Little b", value: "littleB" },
  { label: "Logo", value: "logo" },
  { label: "Logtalk", value: "logtalk" },
  { label: "LPC", value: "lpc" },
  { label: "LSE", value: "lse" },
  { label: "LSL", value: "lsl" },
  { label: "LiveCode", value: "liveCode" },
  { label: "LiveScript", value: "liveScript" },
  { label: "Lua", value: "lua" },
  { label: "Lucid", value: "lucid" },
  { label: "Lustre", value: "lustre" },
  { label: "LYaPAS", value: "lYaPas" },
  { label: "Lynx", value: "lynx" },
  { label: "M2001", value: "m2001" },
  { label: "M4", value: "m4" },
  { label: "Machine code", value: "machineCode" },
  { label: "MAD", value: "mad" },
  { label: "MAD/I", value: "madI" },
  { label: "Magik", value: "magik" },
  { label: "Magma", value: "magma" },
  { label: "make", value: "make" },
  { label: "Maple", value: "maple" },
  { label: "MAPPER", value: "mapper" },
  { label: "MARK-IV", value: "markIv" },
  { label: "Mary", value: "mary" },
  {
    label: "MASM Microsoft Assembly x86",
    value: "masmMicrosoftAssemblyX86",
  },
  { label: "Mathematica", value: "mathematica" },
  { label: "MATLAB", value: "matlab" },
  { label: "Maxima", value: "maxima" },
  { label: "Macsyma", value: "macsyma" },
  { label: "Max", value: "max" },
  { label: "MaxScript", value: "maxScript" },
  { label: "Maya (MEL)", value: "mayaMel" },
  { label: "MDL", value: "mdl" },
  { label: "Mercury", value: "mercury" },
  { label: "Mesa", value: "mesa" },
  { label: "Metacard", value: "metacard" },
  { label: "Metafont", value: "metafont" },
  { label: "MetaL", value: "metaL" },
  { label: "Microcode", value: "microcode" },
  { label: "MicroScript", value: "microScript" },
  { label: "MIIS", value: "miis" },
  { label: "MillScript", value: "millScript" },
  { label: "MIMIC", value: "mimic" },
  { label: "Mirah", value: "mirah" },
  { label: "Miranda", value: "miranda" },
  { label: "MIVA Script", value: "mivaScript" },
  { label: "ML", value: "ml" },
  { label: "Moby", value: "moby" },
  { label: "Model 204", value: "model204" },
  { label: "Modelica", value: "modelica" },
  { label: "Modula", value: "modula" },
  { label: "Modula-2", value: "modula2" },
  { label: "Modula-3", value: "modula3" },
  { label: "Mohol", value: "mohol" },
  { label: "MOO", value: "moo" },
  { label: "Mortran", value: "mortran" },
  { label: "Mouse", value: "mouse" },
  { label: "MPD", value: "mpd" },
  { label: "CIL", value: "cil" },
  { label: "MSL", value: "msl" },
  { label: "MUMPS", value: "mumps" },
  { label: "NASM", value: "nasm" },
  { label: "NATURAL", value: "natural" },
  { label: "Napier88", value: "napier88" },
  { label: "Neko", value: "neko" },
  { label: "Nemerle", value: "nemerle" },
  { label: "nesC", value: "nesC" },
  { label: "NESL", value: "nesl" },
  { label: "Net.Data", value: "netData" },
  { label: "NetLogo", value: "netLogo" },
  { label: "NetRexx", value: "netRexx" },
  { label: "NewLISP", value: "newLisp" },
  { label: "NEWP", value: "newp" },
  { label: "Newspeak", value: "newspeak" },
  { label: "NewtonScript", value: "newtonScript" },
  { label: "NGL", value: "ngl" },
  { label: "Nial", value: "nial" },
  { label: "Nice", value: "nice" },
  { label: "Nickle", value: "nickle" },
  { label: "Nim", value: "nim" },
  { label: "NPL", value: "npl" },
  { label: "Not eXactly C", value: "notEXactlyC" },
  { label: "Not Quite C", value: "notQuiteC" },
  { label: "NSIS", value: "nsis" },
  { label: "Nu", value: "nu" },
  { label: "NWScript", value: "nwScript" },
  { label: "NXT-G", value: "nxtG" },
  { label: "o:XML", value: "oXml" },
  { label: "Oak", value: "oak" },
  { label: "Oberon", value: "oberon" },
  { label: "Obix", value: "obix" },
  { label: "OBJ2", value: "obj2" },
  { label: "Object Lisp", value: "objectLisp" },
  { label: "ObjectLOGO", value: "objectLogo" },
  { label: "Object REXX", value: "objectRexx" },
  { label: "Object Pascal", value: "objectPascal" },
  { label: "Objective-C", value: "objectiveC" },
  { label: "Objective-J", value: "objectiveJ" },
  { label: "Obliq", value: "obliq" },
  { label: "Obol", value: "obol" },
  { label: "OCaml", value: "oCaml" },
  { label: "occam", value: "occam" },
  { label: "occam-π", value: "occamΠ" },
  { label: "Octave", value: "octave" },
  { label: "OmniMark", value: "omniMark" },
  { label: "Onyx", value: "onyx" },
  { label: "Opa", value: "opa" },
  { label: "Opal", value: "opal" },
  { label: "OpenCL", value: "openCl" },
  { label: "OpenEdge ABL", value: "openEdgeAbl" },
  { label: "OPL", value: "opl" },
  { label: "OPS5", value: "ops5" },
  { label: "OptimJ", value: "optimJ" },
  { label: "Orc", value: "orc" },
  { label: "ORCA/Modula-2", value: "orcaModula2" },
  { label: "Oriel", value: "oriel" },
  { label: "Orwell", value: "orwell" },
  { label: "Oxygene", value: "oxygene" },
  { label: "Oz", value: "oz" },
  { label: "P#", value: "p" },
  {
    label: "ParaSail (programming language)",
    value: "paraSailProgrammingLanguage",
  },
  { label: "PARI/GP", value: "pariGp" },
  { label: "Pascal", value: "pascal" },
  { label: "Pawn", value: "pawn" },
  { label: "PCASTL", value: "pcastl" },
  { label: "PCF", value: "pcf" },
  { label: "PEARL", value: "pearl" },
  { label: "PeopleCode", value: "peopleCode" },
  { label: "Perl", value: "perl" },
  { label: "PDL", value: "pdl" },
  { label: "PHP", value: "php" },
  { label: "Phrogram", value: "phrogram" },
  { label: "Pico", value: "pico" },
  { label: "Picolisp", value: "picolisp" },
  { label: "Pict", value: "pict" },
  { label: "Pike", value: "pike" },
  { label: "PIKT", value: "pikt" },
  { label: "PILOT", value: "pilot" },
  { label: "Pipelines", value: "pipelines" },
  { label: "Pizza", value: "pizza" },
  { label: "PL-11", value: "pl11" },
  { label: "PL/0", value: "pl0" },
  { label: "PL/B", value: "plB" },
  { label: "PL/C", value: "plC" },
  { label: "PL/I", value: "plI" },
  { label: "PL/M", value: "plM" },
  { label: "PL/P", value: "plP" },
  { label: "PL/SQL", value: "plSql" },
  { label: "PL360", value: "pl360" },
  { label: "PLANC", value: "planc" },
  { label: "Plankalkül", value: "plankalkul" },
  { label: "Planner", value: "planner" },
  { label: "PLEX", value: "plex" },
  { label: "PLEXIL", value: "plexil" },
  { label: "Plus", value: "plus" },
  { label: "POP-11", value: "pop11" },
  { label: "PostScript", value: "postScript" },
  { label: "PortablE", value: "portablE" },
  { label: "Powerhouse", value: "powerhouse" },
  { label: "PowerBuilder", value: "powerBuilder" },
  { label: "PowerShell", value: "powerShell" },
  { label: "PPL", value: "ppl" },
  { label: "Processing", value: "processing" },
  { label: "Processing.js", value: "processingJs" },
  { label: "Prograph", value: "prograph" },
  { label: "PROIV", value: "proiv" },
  { label: "Prolog", value: "prolog" },
  { label: "PROMAL", value: "promal" },
  { label: "Promela", value: "promela" },
  { label: "PROSE modeling language", value: "proseModelingLanguage" },
  { label: "PROTEL", value: "protel" },
  { label: "ProvideX", value: "provideX" },
  { label: "Pro*C", value: "proC" },
  { label: "Pure", value: "pure" },
  { label: "Python", value: "python" },
  {
    label: "Q (equational programming language)",
    value: "qEquationalProgrammingLanguage",
  },
  {
    label: "Q (programming language from Kx Systems)",
    value: "qProgrammingLanguageFromKxSystems",
  },
  { label: "Qalb", value: "qalb" },
  { label: "QtScript", value: "qtScript" },
  { label: "QuakeC", value: "quakeC" },
  { label: "QPL", value: "qpl" },
  { label: "R", value: "r" },
  { label: "R++", value: "r" },
  { label: "Racket", value: "racket" },
  { label: "RAPID", value: "rapid" },
  { label: "Rapira", value: "rapira" },
  { label: "Ratfiv", value: "ratfiv" },
  { label: "Ratfor", value: "ratfor" },
  { label: "rc", value: "rc" },
  { label: "REBOL", value: "rebol" },
  { label: "Red", value: "red" },
  { label: "Redcode", value: "redcode" },
  { label: "REFAL", value: "refal" },
  { label: "Reia", value: "reia" },
  { label: "Revolution", value: "revolution" },
  { label: "rex", value: "rex" },
  { label: "REXX", value: "rexx" },
  { label: "Rlab", value: "rlab" },
  { label: "RobotC", value: "robotC" },
  { label: "ROOP", value: "roop" },
  { label: "RPG", value: "rpg" },
  { label: "RPL", value: "rpl" },
  { label: "RSL", value: "rsl" },
  { label: "RTL/2", value: "rtl2" },
  { label: "Ruby", value: "ruby" },
  { label: "RuneScript", value: "runeScript" },
  { label: "Rust", value: "rust" },
  { label: "S", value: "s" },
  { label: "S2", value: "s2" },
  { label: "S3", value: "s3" },
  { label: "S-Lang", value: "sLang" },
  { label: "S-PLUS", value: "sPlus" },
  { label: "SA-C", value: "saC" },
  { label: "SabreTalk", value: "sabreTalk" },
  { label: "SAIL", value: "sail" },
  { label: "SALSA", value: "salsa" },
  { label: "SAM76", value: "sam76" },
  { label: "SAS", value: "sas" },
  { label: "SASL", value: "sasl" },
  { label: "Sather", value: "sather" },
  { label: "Sawzall", value: "sawzall" },
  { label: "SBL", value: "sbl" },
  { label: "Scala", value: "scala" },
  { label: "Scheme", value: "scheme" },
  { label: "Scilab", value: "scilab" },
  { label: "Scratch", value: "scratch" },
  { label: "Script.NET", value: "scriptNet" },
  { label: "Sed", value: "sed" },
  { label: "Seed7", value: "seed7" },
  { label: "Self", value: "self" },
  { label: "SenseTalk", value: "senseTalk" },
  { label: "SequenceL", value: "sequenceL" },
  { label: "SETL", value: "setl" },
  { label: "Shift Script", value: "shiftScript" },
  { label: "SIMPOL", value: "simpol" },
  { label: "SIGNAL", value: "signal" },
  { label: "SiMPLE", value: "siMple" },
  { label: "SIMSCRIPT", value: "simscript" },
  { label: "Simula", value: "simula" },
  { label: "Simulink", value: "simulink" },
  { label: "SISAL", value: "sisal" },
  { label: "SLIP", value: "slip" },
  { label: "SMALL", value: "small" },
  { label: "Smalltalk", value: "smalltalk" },
  { label: "Small Basic", value: "smallBasic" },
  { label: "SML", value: "sml" },
  { label: "Snap!", value: "snap" },
  { label: "SNOBOL", value: "snobol" },
  { label: "SPITBOL", value: "spitbol" },
  { label: "Snowball", value: "snowball" },
  { label: "SOL", value: "sol" },
  { label: "Span", value: "span" },
  { label: "SPARK", value: "spark" },
  { label: "Speedcode", value: "speedcode" },
  { label: "SPIN", value: "spin" },
  { label: "SP/k", value: "spK" },
  { label: "SPS", value: "sps" },
  { label: "Squeak", value: "squeak" },
  { label: "Squirrel", value: "squirrel" },
  { label: "SR", value: "sr" },
  { label: "S/SL", value: "sSl" },
  { label: "Stackless Python", value: "stacklessPython" },
  { label: "Starlogo", value: "starlogo" },
  { label: "Strand", value: "strand" },
  { label: "Stata", value: "stata" },
  { label: "Stateflow", value: "stateflow" },
  { label: "Subtext", value: "subtext" },
  { label: "SuperCollider", value: "superCollider" },
  { label: "SuperTalk", value: "superTalk" },
  {
    label: "Swift (Apple programming language)",
    value: "swiftAppleProgrammingLanguage",
  },
  {
    label: "Swift (parallel scripting language)",
    value: "swiftParallelScriptingLanguage",
  },
  { label: "SYMPL", value: "sympl" },
  { label: "SyncCharts", value: "syncCharts" },
  { label: "SystemVerilog", value: "systemVerilog" },
  { label: "T", value: "t" },
  { label: "TACL", value: "tacl" },
  { label: "TACPOL", value: "tacpol" },
  { label: "TADS", value: "tads" },
  { label: "TAL", value: "tal" },
  { label: "Tcl", value: "tcl" },
  { label: "Tea", value: "tea" },
  { label: "TECO", value: "teco" },
  { label: "TELCOMP", value: "telcomp" },
  { label: "TeX", value: "teX" },
  { label: "TEX", value: "tex" },
  { label: "TIE", value: "tie" },
  { label: "Timber", value: "timber" },
  { label: "TMG", value: "tmg" },
  { label: "Tom", value: "tom" },
  { label: "TOM", value: "tom" },
  { label: "Topspeed", value: "topspeed" },
  { label: "TPU", value: "tpu" },
  { label: "Trac", value: "trac" },
  { label: "TTM", value: "ttm" },
  { label: "T-SQL", value: "tSql" },
  { label: "TTCN", value: "ttcn" },
  { label: "Turing", value: "turing" },
  { label: "TUTOR", value: "tutor" },
  { label: "TXL", value: "txl" },
  { label: "TypeScript", value: "typeScript" },
  { label: "Turbo C++", value: "turboC" },
  { label: "Ubercode", value: "ubercode" },
  { label: "UCSD Pascal", value: "ucsdPascal" },
  { label: "Umple", value: "umple" },
  { label: "Unicon", value: "unicon" },
  { label: "Uniface", value: "uniface" },
  { label: "UNITY", value: "unity" },
  { label: "Unix shell", value: "unixShell" },
  { label: "UnrealScript", value: "unrealScript" },
  { label: "Vala", value: "vala" },
  { label: "VBA", value: "vba" },
  { label: "VBScript", value: "vbScript" },
  { label: "Verilog", value: "verilog" },
  { label: "VHDL", value: "vhdl" },
  { label: "Visual Basic", value: "visualBasic" },
  { label: "Visual Basic .NET", value: "visualBasicNet" },
  { label: "Visual DataFlex", value: "visualDataFlex" },
  { label: "Visual DialogScript", value: "visualDialogScript" },
  { label: "Visual Fortran", value: "visualFortran" },
  { label: "Visual FoxPro", value: "visualFoxPro" },
  { label: "Visual J++", value: "visualJ" },
  { label: "Visual J#", value: "visualJ" },
  { label: "Visual Objects", value: "visualObjects" },
  { label: "Visual Prolog", value: "visualProlog" },
  { label: "VSXu", value: "vsXu" },
  { label: "Vvvv", value: "vvvv" },
  { label: "WATFIV, WATFOR", value: "watfivWatfor" },
  { label: "WebDNA", value: "webDna" },
  { label: "WebQL", value: "webQl" },
  { label: "Windows PowerShell", value: "windowsPowerShell" },
  { label: "Winbatch", value: "winbatch" },
  { label: "Wolfram", value: "wolfram" },
  { label: "Wyvern", value: "wyvern" },
  { label: "X++", value: "x" },
  { label: "X#", value: "x" },
  { label: "X10", value: "x10" },
  { label: "XBL", value: "xbl" },
  { label: "XC", value: "xc" },
  { label: "XMOS architecture", value: "xmosArchitecture" },
  { label: "xHarbour", value: "xHarbour" },
  { label: "XL", value: "xl" },
  { label: "Xojo", value: "xojo" },
  { label: "XOTcl", value: "xoTcl" },
  { label: "XPL", value: "xpl" },
  { label: "XPL0", value: "xpl0" },
  { label: "XQuery", value: "xQuery" },
  { label: "XSB", value: "xsb" },
  { label: "XSLT", value: "xslt" },
  { label: "XPath", value: "xPath" },
  { label: "Xtend", value: "xtend" },
  { label: "Yorick", value: "yorick" },
  { label: "YQL", value: "yql" },
  { label: "Z notation", value: "zNotation" },
  { label: "Zeno", value: "zeno" },
  { label: "ZOPL", value: "zopl" },
  { label: "ZPL", value: "zpl" },
];
export const SKILLS = [
  { label: "Git", value: "git" },
  {
    label: "Fullstack Development",
    value: "fullstack",
  },
  {
    label: "Responsive Web Design",
    value: "responsive_web_design",
  },
  {
    label: "RESTful APIs",
    value: "restful_apis",
  },
  {
    label: "SQL",
    value: "sql",
  },
  {
    label: "NoSQL",
    value: "nosql",
  },
  {
    label: "Version Control Systems",
    value: "version_control",
  },
  {
    label: "Agile Methodologies",
    value: "agile_methodologies",
  },
  {
    label: "Problem-Solving",
    value: "problem_solving",
  },
  {
    label: "Communication Skills",
    value: "communication_skills",
  },
  {
    label: "Team Collaboration",
    value: "team_collaboration",
  },
  {
    label: "Critical Thinking",
    value: "critical_thinking",
  },
  {
    label: "React",
    value: "react",
  },
  {
    label: "Django",
    value: "django",
  },
  {
    label: "Vue",
    value: "vue",
  },
];
export const LEVEL = [
  {
    label: "Senior",
    value: "senior",
  },
  {
    label: "Midweight",
    value: "midweight",
  },
  {
    label: "Junior",
    value: "junior",
  },
  {
    label: "Intern",
    value: "intern",
  },
];
export const CONTRACT = [
  {
    label: "Full Time",
    value: "full_time",
  },
  {
    label: "Part Time",
    value: "part_time",
  },
  {
    label: "Contract",
    value: "contract",
  },
];
